import type { OfficeObject } from "./ClickableObject";

export const OBJECTS: OfficeObject[] = [
  {
    id: "desk",
    label: "Chat",
    sublabel: "Talk to your agent",
    position: [0, 0.5, 0],
    size: [2.4, 0.15, 1.2],
    color: "#5C4033",
    emissive: "#E8960D",
    route: "/decision/text",
    icon: "💻",
  },
  {
    id: "inbox",
    label: "Inbox Tray",
    sublabel: "Approvals & drafts",
    position: [-3.2, 0.7, -1],
    size: [1, 0.8, 0.7],
    color: "#D97706",
    emissive: "#F59E0B",
    route: "/dashboard",
    icon: "📥",
  },
  {
    id: "tasks",
    label: "Task Board",
    sublabel: "Action items",
    position: [-3.5, 1.8, -3.8],
    size: [2, 1.4, 0.1],
    color: "#059669",
    emissive: "#10B981",
    route: "/dashboard",
    icon: "📋",
  },
  {
    id: "calendar",
    label: "Calendar",
    sublabel: "Schedule & meetings",
    position: [0, 1.8, -3.8],
    size: [1.6, 1.4, 0.1],
    color: "#2563EB",
    emissive: "#3B82F6",
    route: "/calendar",
    icon: "📅",
  },
  {
    id: "mail",
    label: "Mail Station",
    sublabel: "Email triage",
    position: [3.2, 0.7, -1],
    size: [0.8, 1, 0.6],
    color: "#E11D48",
    emissive: "#F43F5E",
    route: "/email",
    icon: "✉️",
  },
  {
    id: "settings",
    label: "Settings",
    sublabel: "Preferences",
    position: [3.5, 1.8, -3.8],
    size: [1.2, 1.4, 0.1],
    color: "#6B7280",
    emissive: "#9CA3AF",
    route: "/settings",
    icon: "⚙️",
  },
  {
    id: "eod",
    label: "EOD Wrap-Up",
    sublabel: "Summarize your day",
    position: [3.5, 0.4, 2],
    size: [1, 0.6, 0.6],
    color: "#7C3AED",
    emissive: "#8B5CF6",
    route: "/eod-wrapup",
    icon: "🌙",
  },
  {
    id: "sms",
    label: "SMS Log",
    sublabel: "Text history",
    position: [-3.2, 0.4, 2],
    size: [0.7, 0.5, 0.5],
    color: "#0D9488",
    emissive: "#14B8A6",
    route: "/sms-log",
    icon: "📱",
  },
];
