// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Every supabase request gets a hard 60s ceiling. After a tab/PWA suspend the
// underlying socket can be dead, and a fetch on a dead socket hangs forever —
// which leaves queries (and the auth refresh that all queries wait on) stuck.
// 60s (not lower) because LLM-heavy edge functions (email-triage,
// morning-briefing, contacts-sync, steno-summarize) and slow mobile uploads
// can legitimately run tens of seconds — this is an anti-hang backstop, not a
// latency budget. Features that need snappier failure race their own timeouts.
const FETCH_TIMEOUT_MS = 60_000;
const fetchWithTimeout = (input: RequestInfo | URL, init: RequestInit = {}) =>
  fetch(input, {
    ...init,
    signal: init.signal
      ? AbortSignal.any([init.signal, AbortSignal.timeout(FETCH_TIMEOUT_MS)])
      : AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });

// Web Lock intentionally disabled — single-window PWA, and a lock orphaned by
// an OS suspend deadlocks every auth call until full reload. NOTE: omitting
// `lock` (or passing undefined) does NOT disable it — auth-js falls back to
// its default navigatorLock. A passthrough is the only real off switch.
const noOpLock = <R,>(_name: string, _acquireTimeout: number, fn: () => Promise<R>): Promise<R> =>
  fn();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
    lock: noOpLock,
  },
  global: {
    fetch: fetchWithTimeout,
  },
});